/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductRefRouteImport } from './routes/product.$ref'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedGarageRouteImport } from './routes/_authenticated/garage'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRefRoute = ProductRefRouteImport.update({
  id: '/product/$ref',
  path: '/product/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGarageRoute = AuthenticatedGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/cart': typeof AuthenticatedCartRoute
  '/garage': typeof AuthenticatedGarageRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$ref': typeof ProductRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/cart': typeof AuthenticatedCartRoute
  '/garage': typeof AuthenticatedGarageRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$ref': typeof ProductRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/garage': typeof AuthenticatedGarageRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$ref': typeof ProductRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/cart'
    | '/garage'
    | '/category/$slug'
    | '/product/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/cart'
    | '/garage'
    | '/category/$slug'
    | '/product/$ref'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/cart'
    | '/_authenticated/garage'
    | '/category/$slug'
    | '/product/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductRefRoute: typeof ProductRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$ref': {
      id: '/product/$ref'
      path: '/product/$ref'
      fullPath: '/product/$ref'
      preLoaderRoute: typeof ProductRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/garage': {
      id: '/_authenticated/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof AuthenticatedGarageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedGarageRoute: typeof AuthenticatedGarageRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedGarageRoute: AuthenticatedGarageRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductRefRoute: ProductRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
